spring:
  config:
    activate:
      on-profile: local

  application :
    name : lv2-final-mission

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:woowameet
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

open-api:
  holiday :
    base-url : "http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService"
    secret-key : ${HOLIDAY_API_SECRET_KEY}
    connection-timeout : 3
    read-timeout : 15

jwt:
  secret-key : 123456789woowacourse1234567890woowacourse
  expiration : 3600000  # ms, 1??
