spring:
  config:
    activate:
      on-profile: test

  application :
    name : lv2-final-mission

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:woowameet
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

open-api:
  holiday :
    base-url : test
    secret-key : test
    connection-timeout : 1
    read-timeout : 2

jwt:
  secret-key : 123456789woowacourse1234567890woowacourse
  expiration : 3600000  # ms, 1??
